# This file was generated by GoReleaser. DO NOT EDIT.
cask "oursprivacy" do
  version "1.22.0"

  on_macos do
    on_intel do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_macos_amd64.zip"
      sha256 "9273cdd4cb3f7b1699e64af4e679a6d514d65eaa3f4730c8b23d213faded742a"
    end
    on_arm do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_macos_arm64.zip"
      sha256 "de09eba185ef49260df12b920fe2b018823e082e5f12ff948eb7b124a3e323d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_linux_amd64.tar.gz"
      sha256 "a86c955f2edf6b030f99e9a43742ae9bed53f549d91ad39c9978313da93a6f79"
    end
    on_arm do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_linux_arm64.tar.gz"
      sha256 "dc58cff2056458fb3df1ece978980a9cd02c234f81e75a3a27e58fd1ae663659"
    end
  end

  name "oursprivacy"
  desc ""
  homepage "https://oursprivacy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oursprivacy"
  manpage "man/man1/oursprivacy.1.gz"
  bash_completion "completions/oursprivacy.bash"
  fish_completion "completions/oursprivacy.fish"
  zsh_completion "completions/oursprivacy.zsh"

  # No zap stanza required

end
