# This file was generated by GoReleaser. DO NOT EDIT.
cask "oursprivacy" do
  name "oursprivacy"
  desc ""
  homepage "https://oursprivacy.com"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oursprivacy"
  manpage "man/man1/oursprivacy.1.gz"
  bash_completion "completions/oursprivacy.bash"
  zsh_completion "completions/oursprivacy.zsh"
  fish_completion "completions/oursprivacy.fish"

  on_macos do
    on_intel do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_macos_amd64.zip"
      sha256 "02e1a8d8d6f2cd7dea93236bdfe6769c89c022094ca6a095b2ad8163be2f5834"
    end
    on_arm do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_macos_arm64.zip"
      sha256 "7dcec41328f3f0fb2f42770ebfd9fb16d98542ec5c1be2b547506ac805b689b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_linux_amd64.tar.gz"
      sha256 "1fcfc0fa2fc12cfed4bd2b911e942067a7a9c77feca37b729e2111d86b960efe"
    end
    on_arm do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_linux_arm64.tar.gz"
      sha256 "c61e2167e378703847ade3e7015a1706c1ad2b6533c7a3ab763f8b4c93708b67"
    end
  end

  # No zap stanza required
end
