# This file was generated by GoReleaser. DO NOT EDIT.
cask "oursprivacy" do
  version "1.21.0"

  on_macos do
    on_intel do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_macos_amd64.zip"
      sha256 "1b6465445a7e7bf63d08b4c8d5a2ee968de0cae81e0c690002c443ced508bffc"
    end
    on_arm do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_macos_arm64.zip"
      sha256 "ea1e801f1b62eb866f9bcda02a9b6aa0f9ab91d83f8221820b78ee983bc4e1ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_linux_amd64.tar.gz"
      sha256 "597f7705ccb53c6b62107317abb3c207530a3eba892bb7da751946e37f031b4d"
    end
    on_arm do
      url "https://github.com/with-ours/platform-cli/releases/download/v#{version}/oursprivacy_#{version}_linux_arm64.tar.gz"
      sha256 "bc4629c7a7f3c22096c3aa432fbbb169efb1f75307fca0704fada2c4ebcd5db8"
    end
  end

  name "oursprivacy"
  desc ""
  homepage "https://oursprivacy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oursprivacy"
  manpage "man/man1/oursprivacy.1.gz"
  bash_completion "completions/oursprivacy.bash"
  fish_completion "completions/oursprivacy.fish"
  zsh_completion "completions/oursprivacy.zsh"

  # No zap stanza required

end
